spring:
  application:
    name: airBnb

  datasource:
    url: jdbc:postgresql://localhost:5432/airBnb
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 7200000
  refresh-expiration: 604800000

frontend:
  url: http://localhost:8080

stripe:
  secret:
    key: ${STRIPE_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK}

logging:
  level:
    org.springframework.security: DEBUG
